### ISSUE TITLE
Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by elosoman** [hex7c0/mongodb-backup#2]
So when i'm running a backup and specifying collections. It works when the array contains one collection, but when multiple are specified it chokes. I do however get a full tarball downloaded so it would appear the backup finished and sent the stream. 

mongodb-backup is running in meteor and it ends up crashing the server and throwing this error. The bOpts are the options that are sent to backup ... you can see collections is set to the two collections i want to backup.

Thanks, 

I20150415-00:00:17.398(-4)? bOpts.collections: object [ 'exercises', 'exerciseMedia' ]
W20150415-00:00:18.158(-4)? (STDERR) TypeError: Cannot read property 'message' of undefined
W20150415-00:00:18.158(-4)? (STDERR)   at error (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/index.min.js:4:22)
W20150415-00:00:18.158(-4)? (STDERR)   at /app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/index.min.js:86:82
W20150415-00:00:18.158(-4)? (STDERR)   at /app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/index.min.js:55:32
W20150415-00:00:18.158(-4)? (STDERR)   at Array.forEach (native)
W20150415-00:00:18.158(-4)? (STDERR)   at toBson (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/index.min.js:52:42)
W20150415-00:00:18.159(-4)? (STDERR)   at /app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/index.min.js:85:96
W20150415-00:00:18.159(-4)? (STDERR)   at handleCallback (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/lib/utils.js:93:12)
W20150415-00:00:18.159(-4)? (STDERR)   at /app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/lib/cursor.js:571:16
W20150415-00:00:18.159(-4)? (STDERR)   at handleCallback (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
W20150415-00:00:18.159(-4)? (STDERR)   at setCursorDeadAndNotified (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:424:3)
W20150415-00:00:18.159(-4)? (STDERR)   at [object Object].Cursor.next (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7)
W20150415-00:00:18.159(-4)? (STDERR)   at fetchDocs (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/lib/cursor.js:567:10)
W20150415-00:00:18.160(-4)? (STDERR)   at /app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/lib/cursor.js:583:7
W20150415-00:00:18.160(-4)? (STDERR)   at handleCallback (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
W20150415-00:00:18.160(-4)? (STDERR)   at [object Object].Cursor.next (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:603:5)
W20150415-00:00:18.160(-4)? (STDERR)   at /app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:540:12
W20150415-00:00:18.160(-4)? (STDERR)   at queryCallback (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:215:5)
W20150415-00:00:18.160(-4)? (STDERR)   at [object Object].Callbacks.emit (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)
W20150415-00:00:18.160(-4)? (STDERR)   at [object Object].messageHandler (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:209:23)
W20150415-00:00:18.161(-4)? (STDERR)   at Socket.<anonymous> (/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:256:22)
W20150415-00:00:18.161(-4)? (STDERR)   at Socket.emit (events.js:95:17)
W20150415-00:00:18.161(-4)? (STDERR)   at Socket.<anonymous> (_stream_readable.js:765:14)
W20150415-00:00:18.161(-4)? (STDERR)   at Socket.emit (events.js:92:17)
W20150415-00:00:18.161(-4)? (STDERR)   at emitReadable_ (_stream_readable.js:427:10)
W20150415-00:00:18.161(-4)? (STDERR)   at emitReadable (_stream_readable.js:423:5)
W20150415-00:00:18.161(-4)? (STDERR)   at readableAddChunk (_stream_readable.js:166:9)
W20150415-00:00:18.162(-4)? (STDERR)   at Socket.Readable.push (_stream_readable.js:128:10)
W20150415-00:00:18.162(-4)? (STDERR)   at TCP.onread (net.js:529:21)

Suggestions?

**Comment by hex7c0** [comment]
hey @elosoman, sorry for delay
mmm I've tried with multiple collections https://travis-ci.org/hex7c0/mongodb-backup and it works
maybe @hitchcott can help?

however can you enable `logger` options and show the output?

**Comment by elosoman** [comment]
So ... i've been trying to upgrade his package to pass along the collections, query, and drop options. No problem when i don't include collections or if i pass just a single collection (i.e., ['users']). 

Should there be a problem with collections: [] ?

I added log ... first time it didn't write to the log ... then i got the following after performing a single collection backup and then a multi collection backup.

Thanks ... here is the log ...

--- Single collection backup

2015-04-16T04:01:07.348Z - info: backup start
2015-04-16T04:01:07.456Z - info: [INFO-Server:69413] 1429156867456 server 127.0.0.1:3001 connected with ismaster [{"setName":"meteor","setVersion":1,"ismaster":true,"secondary":false,"hosts":["127.0.0.1:3001"],"primary":"127.0.0.1:3001","me":"127.0.0.1:3001","maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":1000,"localTime":"2015-04-16T04:01:07.454Z","maxWireVersion":2,"minWireVersion":0,"ok":1}]
2015-04-16T04:01:07.466Z - info: [INFO-Server:69413] 1429156867466 server 127.0.0.1:3001 connected with ismaster [{"setName":"meteor","setVersion":1,"ismaster":true,"secondary":false,"hosts":["127.0.0.1:3001"],"primary":"127.0.0.1:3001","me":"127.0.0.1:3001","maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":1000,"localTime":"2015-04-16T04:01:07.466Z","maxWireVersion":2,"minWireVersion":0,"ok":1}]
2015-04-16T04:01:07.467Z - info: [INFO-ReplSet:69413] 1429156867467 [1] connected to 127.0.0.1:3001
2015-04-16T04:01:07.468Z - info: [INFO-ReplSet:69413] 1429156867468 [1] updating replicaset state {"primary":null,"secondaries":[]}
2015-04-16T04:01:07.468Z - info: [INFO-ReplSet:69413] 1429156867468 [1] promoting 127.0.0.1:3001 to primary
2015-04-16T04:01:07.469Z - info: db open
2015-04-16T04:01:07.470Z - info: select collection exercises
2015-04-16T04:01:07.470Z - info: make dir at /Volumes/elOsoGrande/Users/ben/Documents/tbiRaftProject/compoundTherapy/TBiRaft-Meteor/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/dump/meteor/exercises/
2015-04-16T04:01:07.482Z - info: db close
2015-04-16T04:01:07.482Z - info: [INFO-ReplSet:69413] 1429156867482 [1] destroyed
2015-04-16T04:01:07.488Z - info: send tar file to stream
2015-04-16T04:01:07.561Z - info: backup stop

--- Multiple collection backup

2015-04-16T04:01:50.047Z - info: backup start
2015-04-16T04:01:50.051Z - info: [INFO-Server:69413] 1429156910051 server 127.0.0.1:3001 connected with ismaster [{"setName":"meteor","setVersion":1,"ismaster":true,"secondary":false,"hosts":["127.0.0.1:3001"],"primary":"127.0.0.1:3001","me":"127.0.0.1:3001","maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":1000,"localTime":"2015-04-16T04:01:50.051Z","maxWireVersion":2,"minWireVersion":0,"ok":1}]
2015-04-16T04:01:50.058Z - info: [INFO-Server:69413] 1429156910058 server 127.0.0.1:3001 connected with ismaster [{"setName":"meteor","setVersion":1,"ismaster":true,"secondary":false,"hosts":["127.0.0.1:3001"],"primary":"127.0.0.1:3001","me":"127.0.0.1:3001","maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":1000,"localTime":"2015-04-16T04:01:50.057Z","maxWireVersion":2,"minWireVersion":0,"ok":1}]
2015-04-16T04:01:50.058Z - info: [INFO-ReplSet:69413] 1429156910058 [2] connected to 127.0.0.1:3001
2015-04-16T04:01:50.058Z - info: [INFO-ReplSet:69413] 1429156910058 [2] updating replicaset state {"primary":null,"secondaries":[]}
2015-04-16T04:01:50.059Z - info: [INFO-ReplSet:69413] 1429156910059 [2] promoting 127.0.0.1:3001 to primary
2015-04-16T04:01:50.059Z - info: db open
2015-04-16T04:01:50.059Z - info: make dir at /Volumes/elOsoGrande/Users/ben/Documents/tbiRaftProject/compoundTherapy/TBiRaft-Meteor/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/dump/meteor/
2015-04-16T04:01:50.060Z - info: select collection exercises
2015-04-16T04:01:50.060Z - info: select collection users
2015-04-16T04:01:50.060Z - info: make dir at /Volumes/elOsoGrande/Users/ben/Documents/tbiRaftProject/compoundTherapy/TBiRaft-Meteor/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/dump/meteor/exercises/
2015-04-16T04:01:50.062Z - info: make dir at /Volumes/elOsoGrande/Users/ben/Documents/tbiRaftProject/compoundTherapy/TBiRaft-Meteor/app/.meteor/local/isopacks/hitchcott_app-dump/npm/node_modules/mongodb-backup/dump/meteor/users/
2015-04-16T04:01:50.137Z - info: db close
2015-04-16T04:01:50.137Z - info: [INFO-ReplSet:69413] 1429156910137 [2] destroyed
2015-04-16T04:01:50.142Z - info: send tar file to stream
2015-04-16T04:01:50.204Z - info: backup stop

**Comment by hex7c0** [comment]
mmm logs seems ok
which version of node and mongo are you using?

can you send me a dump of this collections?

**Comment by hex7c0** [comment]
news?
