### ISSUE TITLE
Error [MongoError]: Unsupported OP_QUERY command: listCollections.

### ISSUE THREAD

**Issue by m0x61h0x64i** [hex7c0/mongodb-backup#51]
Error [MongoError]: Unsupported OP_QUERY command: listCollections. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
    at Function.MongoError.create (C:\Users\user\Desktop\poetry\node_modules\mongodb-core\lib\error.js:31:11)
    at queryCallback (C:\Users\user\Desktop\poetry\node_modules\mongodb-core\lib\cursor.js:212:36)
    at C:\Users\user\Desktop\poetry\node_modules\mongodb-core\lib\connection\pool.js:455:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  ok: 0,
  errmsg: 'Unsupported OP_QUERY command: listCollections. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal',
  code: 352,
  codeName: 'UnsupportedOpQueryCommand'
}

`"mongodb-backup": "^1.6.9"`

**Comment by maxis7567** [comment]
I got the same error

**Comment by gabrielfava** [comment]
same here

**Comment by anotherbird** [comment]
same..
mongod --version
```
Build Info: {
    "version": "6.0.4",
    "gitVersion": "44ff59461c1353638a71e710f385a566bcd2f547",
    "openSSLVersion": "OpenSSL 1.1.1f  31 Mar 2020",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "ubuntu2004",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
```

**Comment by Bonjour123** [comment]
Any maintainer to answer ? Maybe it is no more maintained ? Then it should be stated in the docs..
